name: gaa
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.5.3
  # Firebase Packages
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_database: ^10.3.4
  google_sign_in: ^6.1.6

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  geolocator: ^10.1.1
  http: ^1.1.0
  google_maps_place_picker_mb: ^3.1.2
  google_maps_flutter_android: ^2.6.2
  google_maps_flutter_platform_interface: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/ 

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
